// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzkzwtmzqysvhdsbrfzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6a3p3dG16cXlzdmhkc2JyZnpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NDUwMzYsImV4cCI6MjA1NTIyMTAzNn0.89T3oEztRY3p0mNJysVek353_KO7fs_Ysna1Hzlsw0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);